# page configuration

author: Noah Nagel

# optional configuration 

sass:
    sass_dir: _sass
    style: compressed

# github stuff
baseurl: "/chardisco"  # Leave this empty for user or organization site, or set it to "/repository-name" for project site
url: "https://nosehad.github.io"  # Replace with your GitHub Pages URL
